services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      NEXT_PUBLIC_TMDB_API_KEY: ${NEXT_PUBLIC_TMDB_API_KEY}
      NEXT_PUBLIC_TMDB_BASE_URL: ${NEXT_PUBLIC_TMDB_BASE_URL}
      NEXT_PUBLIC_TMDB_IMAGE_BASE_URL: ${NEXT_PUBLIC_TMDB_IMAGE_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "bunx drizzle-kit migrate && bun server.js"

  db:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
